package com.instacraft.uuidguard;

public enum DecisionType {
    ALLOW_REGISTER,
    ALLOW_MATCH,
    ALLOW_MIGRATE_BEDROCK_OFFLINE_UUID,
    ALLOW_DATABASE_UNAVAILABLE,
    BLOCK_CROSS_PLATFORM_NAME,
    BLOCK_UUID_MISMATCH,
    BLOCK_DATABASE_UNAVAILABLE
}
